export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'
export const GET_HOT_RECOMMENDS = "GET_HOT_RECOMMENDS"
export const GET_NEW_ALBUM = "GET_NEW_ALBUM"


export const  CHANGE_UP_RANKING = "CHANGE_UP_RANKING"
export const  CHANGE_NEW_RANKING =  "CHANGE_NEW_RANKING"
export const  CHANGE_ORIGINAL_RANKING = "CHANGE_ORIGINAL_RANKING"